## OBTENCIÓN DE DATOS

In [5]:
import json
import pandas as pd
import requests

pd.set_option('display.max_columns', None)

Para el proyecto, obtenemos los datasets de la API de NOAA (National Centers for Enviromental Information).

https://www.ngdc.noaa.gov/hazel/view/swagger

In [6]:
# Comprobación de que la web y nuestra llamada funcionan correctamente.

base_url = "http://www.ngdc.noaa.gov/hazel"
endpoint_earthquake = "/hazard-service/api/v1/earthquakes"

url_earthquake = base_url + endpoint_earthquake
print(url_earthquake)
respuesta_earthquake = requests.get(url_earthquake)

http://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/earthquakes

In [7]:
print(respuesta_earthquake.status_code)

200

In [8]:
# Obtención de la información necesaria.

base_url = "https://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/earthquakes"
items_per_page = 200
page = 1
all_items = []

while True:
    params = {
        "itemsPerPage": items_per_page,
        "page": page
    }
    print(f"Descargando página {page}...")
    response = requests.get(base_url, params=params)
    data = response.json()
    
    items = data.get("items", [])
    if not items:
        print("No hay más datos.")
        break
    
    all_items.extend(items)
    page += 1

print(f"Total registros descargados: {len(all_items)}")

filename = "earthquakes_api.json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(all_items, f, ensure_ascii=False, indent=2)

print(f"Datos guardados en {filename}")

Descargando página 1...
Descargando página 2...
Descargando página 3...
Descargando página 4...
Descargando página 5...
Descargando página 6...
Descargando página 7...
Descargando página 8...
Descargando página 9...
Descargando página 10...
Descargando página 11...
Descargando página 12...
Descargando página 13...
Descargando página 14...
Descargando página 15...
Descargando página 16...
Descargando página 17...
Descargando página 18...
Descargando página 19...
Descargando página 20...
Descargando página 21...
Descargando página 22...
Descargando página 23...
Descargando página 24...
Descargando página 25...
Descargando página 26...
Descargando página 27...
Descargando página 28...
Descargando página 29...
Descargando página 30...
Descargando página 31...
Descargando página 32...
Descargando página 33...
Descargando página 34...
Descargando página 35...
No hay más datos.
Total registros descargados: 6605
Datos guardados en earthquakes_api.json

In [9]:
# Comprobamos el dataset de terremotos obtenido

with open("earthquakes_api.json", "r", encoding="utf-8") as f:
    data = json.load(f)

#Convertimos lista de diccionarios a DataFrame
earthquake = pd.DataFrame(data)

In [10]:
earthquake

,id,year,locationName,latitude,longitude,eqMagnitude,damageAmountOrder,eqMagUnk,publish,country,regionCode,intensity,deathsAmountOrder,tsunamiEventId,deathsAmountOrderTotal,eqDepth,deaths,housesDestroyedAmountOrder,eqMagMs,deathsTotal,damageAmountOrderTotal,housesDestroyedAmountOrderTotal,month,day,volcanoEventId,eqMagMl,housesDamagedAmountOrder,injuries,injuriesAmountOrder,injuriesTotal,injuriesAmountOrderTotal,hour,housesDamagedAmountOrderTotal,minute,eqMagMw,housesDestroyed,housesDamaged,housesDestroyedTotal,housesDamagedTotal,area,second,eqMagMfa,damageMillionsDollars,missing,missingAmountOrder,missingTotal,missingAmountOrderTotal,damageMillionsDollarsTotal,eqMagMb
0,1,-2150,"JORDAN: BAB-A-DARAA,AL-KARAK",31.100,35.500,7.3,3.0,7.3,True,JORDAN,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,-2000,SYRIA: UGARIT,35.683,35.800,NaN,NaN,NaN,True,SYRIA,140,10.0,3.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,-2000,TURKMENISTAN: W,38.000,58.200,7.1,1.0,NaN,True,TURKMENISTAN,40,10.0,1.0,NaN,1.0,18.0,1.0,1.0,7.1,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,-1566,ISRAEL: ARIHA (JERICHO),31.500,35.300,NaN,3.0,NaN,True,ISRAEL,140,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,-1450,ITALY: LACUS CIMINI,35.500,25.500,NaN,NaN,NaN,True,ITALY,130,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6600,10923,2025,RUSSIA: KAMCHATKA PENINSULA,52.512,160.324,8.8,NaN,NaN,True,RUSSIA,50,8.0,NaN,6044.0,1.0,35.0,NaN,NaN,8.0,1.0,2.0,NaN,7.0,29.0,NaN,NaN,NaN,NaN,NaN,13.0,1.0,23.0,NaN,24.0,8.8,NaN,NaN,NaN,NaN,NaN,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
6601,10924,2025,TURKEY: BALIKESIR,39.312,28.069,6.1,2.0,NaN,True,TURKEY,140,NaN,1.0,NaN,1.0,10.0,1.0,1.0,NaN,1.0,2.0,1.0,8.0,10.0,NaN,NaN,NaN,29.0,1.0,29.0,1.0,16.0,NaN,53.0,6.1,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6602,10925,2025,EL SALVADOR-GUATEMALA,14.055,-89.883,5.7,3.0,NaN,True,GUATEMALA,100,NaN,1.0,NaN,1.0,10.0,1.0,NaN,NaN,1.0,3.0,NaN,7.0,29.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,21.0,4.0,25.0,5.7,NaN,1200.0,NaN,1200.0,NaN,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6603,10926,2025,INDONESIA: SULAWESI: POSO,-1.282,120.727,5.8,2.0,NaN,True,INDONESIA,170,NaN,1.0,6046.0,1.0,8.0,1.0,1.0,NaN,1.0,2.0,1.0,8.0,16.0,NaN,NaN,1.0,41.0,1.0,41.0,1.0,22.0,1.0,38.0,5.8,12.0,33.0,12.0,33.0,NaN,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6604,10927,2025,CHILE: DRAKE PASSAGE,-60.186,-61.821,7.5,NaN,NaN,True,ANTARCTICA,20,NaN,NaN,6047.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,16.0,7.5,NaN,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Guardamos el dataframe en un archivo csv

earthquake.to_csv("earthquakeraw.csv", index=False, encoding="utf-8")

Hacemos lo mismo para los datos de Tsunamis

In [12]:
base_url = "https://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/tsunamis/events"
items_per_page = 200
page = 1
all_items = []

while True:
    params = {
        "itemsPerPage": items_per_page,
        "page": page
    }
    print(f"Descargando página {page}...")
    response = requests.get(base_url, params=params)
    data = response.json()
    
    items = data.get("items", [])
    if not items:
        print("No hay más datos.")
        break
    
    all_items.extend(items)
    page += 1

print(f"Total registros descargados: {len(all_items)}")

filename = "tsunami_api.json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(all_items, f, ensure_ascii=False, indent=2)

print(f"Datos guardados en {filename}")

Descargando página 1...
Descargando página 2...
Descargando página 3...
Descargando página 4...
Descargando página 5...
Descargando página 6...
Descargando página 7...
Descargando página 8...
Descargando página 9...
Descargando página 10...
Descargando página 11...
Descargando página 12...
Descargando página 13...
Descargando página 14...
Descargando página 15...
Descargando página 16...
No hay más datos.
Total registros descargados: 2989
Datos guardados en tsunami_api.json

In [13]:
# Comprobamos los datos obtenidos de tsunamis

with open("tsunami_api.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Convertimos lista de diccionarios a DataFrame
tsunami = pd.DataFrame(data)

In [14]:
tsunami

,id,year,eventValidity,causeCode,earthquakeEventId,numDeposits,country,locationName,regionCode,latitude,longitude,numRunups,tsIntensity,deathsAmountOrder,damageAmountOrder,deathsAmountOrderTotal,damageAmountOrderTotal,publish,oceanicTsunami,volcanoEventId,maxWaterHeight,eqMagnitude,month,housesDestroyedAmountOrder,deathsTotal,housesDestroyedAmountOrderTotal,day,tsMtIi,deaths,eqDepth,housesDamagedAmountOrder,housesDamagedAmountOrderTotal,housesDestroyed,housesDestroyedTotal,hour,minute,area,injuries,injuriesAmountOrder,injuriesTotal,injuriesAmountOrderTotal,housesDamaged,housesDamagedTotal,second,missingTotal,missingAmountOrderTotal,damageMillionsDollarsTotal,tsMtAbe,damageMillionsDollars,warningStatusId,missing,missingAmountOrder
0,1,-2000,1,1.0,2.0,0,SYRIA,SYRIAN COASTS,50.0,35.683,35.800,1,6.0,3.0,4.0,3.0,4.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,-1610,4,6.0,5877.0,28,GREECE,THERA ISLAND (SANTORINI),50.0,36.400,25.400,2,6.0,3.0,3.0,3.0,3.0,True,True,1351.0,90.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,-1365,1,2.0,9712.0,0,SYRIA,SYRIAN COASTS,50.0,35.683,35.800,1,6.0,NaN,2.0,NaN,3.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,-1300,2,0.0,NaN,0,TURKEY,"IONIAN COASTS, TROAD",50.0,39.960,26.240,0,5.0,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,-760,2,0.0,NaN,0,ISRAEL,ISRAEL AND LEBANON COASTS,50.0,NaN,NaN,0,3.0,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2984,6043,2006,-1,1.0,10922.0,0,BRAZIL,ARQUIPELAGO SAO PEDRO E SAO PAULO,71.0,1.175,-28.065,0,NaN,NaN,NaN,NaN,1.0,True,True,NaN,NaN,6.0,6.0,NaN,NaN,NaN,5.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,6.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,6044,2025,4,1.0,10923.0,0,RUSSIA,"KAMCHATKA PENINSULA, RUSSIA",86.0,52.512,160.324,332,NaN,1.0,2.0,1.0,2.0,True,True,NaN,19.00,8.8,7.0,NaN,1.0,NaN,29.0,NaN,1.0,35.0,NaN,NaN,NaN,NaN,23.0,24.0,NaN,13.0,1.0,13.0,1.0,NaN,NaN,52.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2986,6045,2025,4,8.0,NaN,0,USA,"TRACY ARM, AK",87.0,57.840,-133.060,3,NaN,NaN,1.0,NaN,1.0,True,True,NaN,30.00,NaN,8.0,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,26.0,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,6046,2025,3,1.0,10926.0,0,INDONESIA,SULAWESI,83.0,-1.282,120.727,1,NaN,NaN,NaN,1.0,2.0,True,True,NaN,0.02,5.8,8.0,NaN,1.0,1.0,16.0,NaN,NaN,8.0,NaN,1.0,NaN,12.0,22.0,38.0,NaN,NaN,NaN,41.0,1.0,NaN,33.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2988,6047,2025,4,1.0,10927.0,0,ANTARCTICA,DRAKE PASSAGE,71.0,-60.186,-61.821,2,NaN,NaN,NaN,NaN,NaN,True,True,NaN,0.13,7.5,8.0,NaN,NaN,NaN,22.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,2.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [15]:
# Guardamos el dataframe en un archivo csv

tsunami.to_csv("tsunamiraw.csv", index=False, encoding="utf-8")